[project]
name = "analisi-costi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"gspread>=6.2.1",
	"oauth2client>=4.1.3",
	"pandas>=2.3.3",
	"plotly>=6.5.0",
	"streamlit>=1.25.0",
]
